// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKP7L6AGIfaPHUizVmchZ8z5C46PhcNH0',
    appId: '1:533583165885:web:b4a2d8e18a1416ee6bfad4',
    messagingSenderId: '533583165885',
    projectId: 'login-app-d5d2c',
    authDomain: 'login-app-d5d2c.firebaseapp.com',
    storageBucket: 'login-app-d5d2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfP4T9-Yw9j7IW9lyw9dDpYtLhZuroF5s',
    appId: '1:533583165885:android:edc015bbedecdb3b6bfad4',
    messagingSenderId: '533583165885',
    projectId: 'login-app-d5d2c',
    storageBucket: 'login-app-d5d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMinyF9v3F0KKkihTd1CTAs5yr30QSoI',
    appId: '1:533583165885:ios:62d71b210a9035f46bfad4',
    messagingSenderId: '533583165885',
    projectId: 'login-app-d5d2c',
    storageBucket: 'login-app-d5d2c.firebasestorage.app',
    iosBundleId: 'com.example.egrocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQMinyF9v3F0KKkihTd1CTAs5yr30QSoI',
    appId: '1:533583165885:ios:62d71b210a9035f46bfad4',
    messagingSenderId: '533583165885',
    projectId: 'login-app-d5d2c',
    storageBucket: 'login-app-d5d2c.firebasestorage.app',
    iosBundleId: 'com.example.egrocery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKP7L6AGIfaPHUizVmchZ8z5C46PhcNH0',
    appId: '1:533583165885:web:1fe5190e58ee1db36bfad4',
    messagingSenderId: '533583165885',
    projectId: 'login-app-d5d2c',
    authDomain: 'login-app-d5d2c.firebaseapp.com',
    storageBucket: 'login-app-d5d2c.firebasestorage.app',
  );
}
